version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  update_configs:
    build: ../common/ruby
    command: bash -c "/usr/app/bin/update_config.rb api-node && touch /state/update_configs"

    environment:
    - S3_PEERS_FILE=s3://symbol-testnet/testnet-0963-v1/peer-list/peers-p2p.json

    volumes:
    - ./runtime-vars:/usr/app/config
    - ../identity:/usr/app/identity
    - ./api-node:/usr/app/api-node
    - ./rest-gateway:/usr/app/rest-gateway
    - ./state:/state:rw

  ###### running services ###########
  api-node:
    image: techbureau/catapult-server:gcc-0.9.6.3
    ports:
    - 7900:7900
    command: bash -c "/bin-mount/wait /state/update_configs && /bin/bash /userconfig/startApiServer.sh"
    stop_signal: SIGINT
    restart: on-failure:2
    volumes:
    - ../utilities/bin/bash:/bin-mount
    - ./api-node/userconfig:/userconfig/
    - ../identity/cert:/userconfig/resources/cert
    - ./data/api-node:/data:rw
    - ./state:/state:rw
    - ./data/debug:/usr/share/apport/apport:rw
    depends_on:
    - api-broker

  api-broker:
    image: techbureau/catapult-server:gcc-0.9.6.3
    command: bash -c "/bin-mount/wait /state/update_configs && /bin/bash /userconfig/runServerRecover.sh && /bin/bash /userconfig/startBroker.sh"
    ports:
    - 7902:7902
    stop_signal: SIGINT
    restart: on-failure:2
    volumes:
    - ../utilities/bin/bash:/bin-mount
    - ./api-node/userconfig:/userconfig/
    - ../identity/cert:/userconfig/resources/cert
    - ./data/api-node:/data:rw
    - ./state:/state:rw
    - ./data/debug:/usr/share/apport/apport:rw

  db:
    image: mongo:4.2.6-bionic
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ../utilities/bin/bash:/bin-mount
    - ./data/mongo:/dbdata:rw

  init-db:
    image: mongo:4.2.6-bionic
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./utilities/bin/bash:/bin-mount
    - ./data/mongo:/dbdata:rw
    - ./mongo/configs/:/userconfig/:ro
    depends_on:
    - db

  rest-gateway:
    image: symbolplatform/symbol-rest-nightly:commit-5eb7eac
    command: ash -c "/bin-mount/wait /state/update_configs && npm start /userconfig/rest.json"
    stop_signal: SIGINT
    ports:
    - "3000:3000"
    volumes:
    - ./rest-gateway/userconfig/:/userconfig/
    - ../utilities/bin/ash:/bin-mount
    - ./state:/state:rw
    - ./data/rest-gateway:/logs:rw
    - ./api-node/userconfig/resources:/api-node-config/
    - ../identity/cert:/api-node-config/cert
    depends_on:
    - init-db
    networks:
      default:
        ipv4_address: 172.20.0.9
